##===- tools/opt/Makefile ----------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##
LEVEL = ../..
TOOLNAME = opt
USES_CPLEX := 1

LINK_COMPONENTS := bitreader bitwriter asmparser instrumentation scalaropts ipo

include $(LEVEL)/Makefile.common
